### ISSUE TITLE
Training not working

### ISSUE THREAD

**Issue by amal-k-ajay** [iballester/SPiKE#5]
I installed everything as per the instructions and extracted the ITOP dataset. But when I run the train_itop.py script, I get 4 different errors each time. Most commonly "RuntimeError: CUDA error: an illegal memory access was encountered". Does anyone know what can be the root cause here?

I have the below versions of dependencies.
Python: 3.8.10
g++: 11.4.0
PyTorch: 1.8.1+cu111

Errors:

```
Start training
Epoch: [0]:  44%|████████████████████████████████████████▍                                                   | 329/748 [02:39<03:22,  2.07it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 133, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 63, in main
    train_clip_loss, train_pck, train_map = train_one_epoch(
  File "/home/user/Desktop/Amal/SPiKE/trainer_itop.py", line 29, in train_one_epoch
    total_pck += pck.detach().cpu().numpy()
RuntimeError: CUDA error: misaligned address

Start training
Epoch: [0]:   0%|                                                                                                      | 0/748 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 133, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 63, in main
    train_clip_loss, train_pck, train_map = train_one_epoch(
  File "/home/user/Desktop/Amal/SPiKE/trainer_itop.py", line 35, in train_one_epoch
    total_loss += loss.item()
RuntimeError: CUDA error: device-side assert triggered

Start training
Epoch: [0]:  66%|████████████████████████████████████████████████████████████▍                               | 491/748 [03:20<01:45,  2.44it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 133, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 63, in main
    train_clip_loss, train_pck, train_map = train_one_epoch(
  File "/home/user/Desktop/Amal/SPiKE/trainer_itop.py", line 35, in train_one_epoch
    total_loss += loss.item()
RuntimeError: CUDA error: an illegal memory access was encountered

Start training
Epoch: [0]:  62%|████████████████████████████████████████████████████████▊                                   | 462/748 [03:44<02:18,  2.06it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 133, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 63, in main
    train_clip_loss, train_pck, train_map = train_one_epoch(
  File "/home/user/Desktop/Amal/SPiKE/trainer_itop.py", line 35, in train_one_epoch
    total_loss += loss.item()
RuntimeError: CUDA error: unspecified launch failure
```

**Comment by iballester** [comment]
Hi Amal, I'm sorry to read that the training script is not working for you. I've tried running the train_itop.py script with the same dependencies you listed (Python 3.8.10, g++ 11.4.0, PyTorch 1.8.1+cu111), and it's training in my system.

My first suggestion would be to check that the data is somehow not corrupted. Have you tried to visualize the point clouds? Also, is it possible that your GPU is running out of memory? Have you tried to reduce the batch size?

**Comment by amal-k-ajay** [comment]
Hello Irene, 

Thank you for your reply. Yes, I tried to visualize the point clouds and it works. I also tried reducing the batch size but I still get the errors eventually.

The most epochs I could reach was epoch 1 as shown below.

```
Start training
Epoch: [0]: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2992/2992 [05:03<00:00,  9.85it/s]

Test: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 809/809 [01:11<00:00, 11.27it/s]

Epoch 0 - Train Loss: nan
Epoch 0 - Train mAP: 0.0000
Epoch 0 - Train PCK: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Epoch 0 - Validation Loss: nan
Epoch 0 - Validation mAP: 0.0000
Epoch 0 - Validation PCK: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Epoch: [1]:  62%|████████████████████████████████████████████████████████████████████████████████████████████▊                                                        | 1863/2992 [03:09<01:54,  9.83it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 133, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/train_itop.py", line 63, in main
    train_clip_loss, train_pck, train_map = train_one_epoch(
  File "/home/user/Desktop/Amal/SPiKE/trainer_itop.py", line 35, in train_one_epoch
    total_loss += loss.item()
RuntimeError: CUDA error: misaligned address
```

I'm working on Ubuntu 20.04, CUDA 11.1 (nvcc --version),  NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4  (nvidia-smi), NVIDIA GeForce RTX 2080 Ti with 11 GB memory.

**Comment by amal-k-ajay** [comment]
I got the below results and errors for predict_itop.py script.

```
Log dir: /home/user/Desktop/Amal/SPiKE/experiments/ITOP-SIDE/1/log
CUDA_VISIBLE_DEVICES: 0
Loading data from /home/user/Desktop/Amal/SPiKE/datasets/SIDE/
Loading test point clouds: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10501/10501 [00:03<00:00, 2965.35it/s]
Using only frames labeled as valid. From the total of 10501 test frames using 4854 valid joints
Loading model from experiments/ITOP-SIDE/pre-trained/best_model.pth
Test: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 203/203 [00:45<00:00,  4.43it/s]
Validation Loss: nan
Validation mAP: 0.0014
Validation PCK: [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.02060157 0.        ]


Log dir: /home/user/Desktop/Amal/SPiKE/experiments/ITOP-SIDE/1/log
CUDA_VISIBLE_DEVICES: 0
Loading data from /home/user/Desktop/Amal/SPiKE/datasets/SIDE/
Loading test point clouds: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10501/10501 [00:03<00:00, 2889.09it/s]
Using only frames labeled as valid. From the total of 10501 test frames using 4854 valid joints
Loading model from experiments/ITOP-SIDE/pre-trained/best_model.pth
Test:   4%|███████                                                                                                                                                        | 9/203 [00:04<01:28,  2.20it/s]
Traceback (most recent call last):
  File "/home/user/Desktop/Amal/SPiKE/predict_itop.py", line 108, in <module>
    main(args)
  File "/home/user/Desktop/Amal/SPiKE/predict_itop.py", line 82, in main
    losses, val_clip_loss, val_map, val_pck = evaluate(
  File "/home/user/Desktop/Amal/SPiKE/predict_itop.py", line 39, in evaluate
    total_pck += pck.detach().cpu().numpy()
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by amal-k-ajay** [comment]
Hi, I tried on a different pc with the below spec and it worked.

Ubuntu 20.04, CUDA 11.1 (nvcc --version), NVIDIA-SMI 470.256.02 Driver Version: 470.256.02 CUDA Version: 11.4 (nvidia-smi), NVIDIA GeForce RTX 3080. Python 3.8.16.
